version: '3.8'
services:
  postgres:
    image: postgres
    container_name: gamereviewcontainer
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5438:5432"
    env_file:
      - .env
    restart: always
